language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
          env: ZEO_MTACCEPTOR=1
        - os: linux
          python: 3.5
          env: ZEO_MTACCEPTOR=1
        - os: linux
          python: 2.7
          env: ZEO4_SERVER=1
        - os: linux
          python: 3.4
          env: ZEO4_SERVER=1
        - os: linux
          python: 3.5
          env: ZEO4_SERVER=1
install:
    - pip install zc.buildout
    - buildout
cache:
  directories:
    - eggs
script:
    - bin/test -v1j99
notifications:
    email: false
