language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='macpython 3.4'
        - os: osx
          language: generic
          env: TERRYFY_PYTHON='homebrew 3'
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then git clone https://github.com/MacPython/terryfy; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/travis_tools.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then get_python_environment $TERRYFY_PYTHON venv; fi
    - if [[ "$TERRYFY_PYTHON" == "homebrew 3" ]]; then alias pip=`which pip3` ; fi
install:
    - pip install -U setuptools
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1j99
notifications:
    email: false
