language: python
sudo: false
python:
    - 3.4
    - 3.5
install:
    - pip install -U setuptools
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -vvv1 -j99
notifications:
    email: false
