language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: 3.4
          env: ZEO_MTACCEPTOR=1
        - os: linux
          python: 3.5
          env: ZEO_MTACCEPTOR=1
install:
    - pip install -U setuptools
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1j99 -t can_use_empty_string_for_local_host_on_client
notifications:
    email: false
