language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
before_install:
    # Workaround for a permissions issue with Travis virtual machine images
    # that breaks Python's multiprocessing:
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm
install:
    - virtualenv env
    - env/bin/pip install -U setuptools distribute
    - env/bin/python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1 -j99
notifications:
    email: false
