language: python
sudo: false
matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5
        - os: linux
          python: pypy
install:
    - pip install zc.buildout
    - buildout
cache:
  directories:
    - eggs
script:
    - bin/test -v1 -j99
notifications:
    email: false
