language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - pypy
install:
    - virtualenv env
    - env/bin/pip install -U setuptools distribute
    - env/bin/python bootstrap.py
    - env/bin/python --version
    - bin/buildout
script:
    - bin/test -v1 -j99
notifications:
    email: false
